# Generated by Django 2.0.1 on 2018-01-09 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='Token')),
                ('token_type', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('EMBED', 'Web')], default='FACEBOOK', max_length=100, verbose_name='Tipo do Token')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Data-Hora de Criação')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Data-Hora de Atualização')),
            ],
            options={
                'verbose_name': 'Cliente',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPENED', 'Aberto'), ('PROCESSED', 'Processado'), ('SENT', 'Enviado'), ('DELIVERED', 'Entregue'), ('CANCELED', 'Cancelado')], default='OPENED', max_length=100, verbose_name='Status')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Data-Hora de Criação')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Data-Hora de Atualização')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.Client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'ordering': ['id', 'status'],
            },
        ),
    ]
