# Generated by Django 2.0.1 on 2018-01-09 03:44

import api.models.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('keyword', models.CharField(max_length=100, unique=True, verbose_name='Palavra Chave')),
                ('category', models.CharField(choices=[('FOOD', 'Lanche'), ('DRINK', 'Bebida'), ('OTHER', 'Outro')], max_length=100, verbose_name='Categoria')),
                ('price', api.models.utils.MoneyField(decimal_places=2, default=0, max_digits=25, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Data-Hora de Criação')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Data-Hora de Atualização')),
            ],
            options={
                'verbose_name': 'Produto',
                'ordering': ['name'],
            },
        ),
    ]
