# Generated by Django 2.0.1 on 2018-01-09 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180109_0353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=25, null=True, verbose_name='Nome')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('source', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('EMBED', 'Web')], default='FACEBOOK', max_length=100, verbose_name='Plataforma')),
                ('session', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sessão')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Data-Hora de Criação')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Data-Hora de Atualização')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Client', verbose_name='Cliente')),
            ],
            options={
                'ordering': [],
                'verbose_name': 'Mensagem',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='keyword',
            field=models.CharField(max_length=25, unique=True, verbose_name='Palavra Chave'),
        ),
    ]
