# Generated by Django 2.0.1 on 2018-01-13 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180113_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=1, verbose_name='Quantidade')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Data-Hora de Criação')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Data-Hora de Atualização')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.Order', verbose_name='Pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='api.Product', verbose_name='Produto')),
            ],
            options={
                'ordering': ['order', 'product'],
                'verbose_name': 'Item',
            },
        ),
    ]
