# Generated by Django 2.0.1 on 2018-02-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180114_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='notify',
            field=models.BooleanField(default=False, verbose_name='Notifica'),
        ),
        migrations.AddField(
            model_name='message',
            name='visualized',
            field=models.BooleanField(default=False, verbose_name='Visualizada'),
        ),
    ]
